### ISSUE TITLE
Only eleven months are availble to upload utility bills (March 2017 is misisng)

### ISSUE THREAD

**Issue by Tamara-Collinsville** [Azavar/beta-ultra#3]

**Comment by muaz-azavar** [comment]
Hi Tamara,

The months available to claimants for uploading utility bills correspond to the rebate configuration, namely the Billing Period in the Rebate Basics (first step when creating/editing a rebate), which defines the beginning and end months (inclusive) of bills related to the rebate.

The Billing Period of "BETA TEST REBATE" is set to Apr 2016 to Feb 2017 (check here: https://ultra-beta.governmenttechsolutions.com/Mun/Rebates/RebateBasics?rebateId=4324406f-a226-4d49-ac7d-a00a448625dd), which is a total of 11 months.
In order to provide claimants with 12 months, this Billing Period should be updated to cover 12 months, and since the rebate is active you'll need to deactivate it, edit it then reactivate it.

I hope this helps!
Muaz

**Comment by muaz-azavar** [comment]
Hi Tamara,

I tried to extend the Billing Period to cover March, but since it is the current month we cannot include it in the Billing Period while keeping the rebate available for claimants because of this rule:
> The Claim Period, which defines when claimants can start submitting claims, must start after the end of the Billing Period because it is not possible to have utility bills for the last month before it ends.

Adding March will require the earliest start of Claim Period to be the first of April and thus make the rebate **unavailable for the next couple of weeks**.

For testing purposes we can do one of the following:
1. Keep the current setting with 11 months, which can be updated once April starts to include March.
2. Set the Billing Period to `Apr 2015 to Mar 2016` and keep the rebate available for claimants.
3. Set the Billing Period to `Mar 2016 to Feb 2017` and keep the rebate available for claimants.
4. Set the Billing Period to `Apr 2016 to Mar 2017` and make the rebate **unavailable** for claimants for now, but this option means no further claims can be submitted for this rebate.

Also, if you think the mentioned rule should be updated please let us know.

Please let me know which option you would like us to apply.
Thanks,
Muaz

**Comment by Tamara-Collinsville** [comment]
The current setting with 11 months is fine for testing.  I just wanted it to be noted so it would be correct when we go live April 3rd.

Thanks!
